### ISSUE TITLE
overwriteBuildSettings not working

### ISSUE THREAD

**Issue by HenryStrattonFW** [onevcat/XUPorter#39]
Hey folks, 

Recently came across the need to update XUPorter, we have a project that requires completely automated builds, (from replace not append). I've added the necessary methods required to generate the entitlements file from a template, set the DevelopmentTeam and SystemCapabilities values in the project file, and add the newly generated entitlements file to the project. So far, all is good.

However the last step which is a crucial one, is telling the build configurations that this file is to be used for the CODE_SIGN_ENTITLEMENTS. I've currently tried this in two ways. The first was to use the overwriteBuildSettings method to push the value in. This doesn't seem to work, and having looked at the code I can see why. However I've moved over to the following snippet instead. 

foreach (KeyValuePair<string, XCBuildConfiguration> buildConfig in buildConfigurations)
            {
                if(buildConfig.Value.data.ContainsKey("CODE_SIGN_ENTITLEMENTS"))
                    buildConfig.Value.data["CODE_SIGN_ENTITLEMENTS"] = path;
                else
                    buildConfig.Value.data.Add("CODE_SIGN_ENTITLEMENTS", path);
            }

This works, and puts the data into the xcode project file, however the path does not automatically get quotes put around it. I attempted to modify the path value by using the following.

path = "\"" + path + "\"";

This was intended add quotes to the path making it valid. However when I do this, the project file that gets exported then wraps this whole thing in quotes, causing double quotes at each end of the path, stopping the project form even opening.

Any Ideas?

**Comment by derFunk** [comment]
There are still features using `CODE_SIGN_ENTITLEMENTS` - e.g. the new iOS 9 [Associated Domains ](https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2) feature, where the linked entitlements file looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:yourlink.com</string>
	</array>
</dict>
</plist>
```
