### ISSUE TITLE
License notice requirement?

### ISSUE THREAD

**Issue by fadookie** [onevcat/XUPorter#43]
Hi, thanks for making XUPorter!
This isn't really an issue but a question (perhaps it could be clarified in your README later on) - do I need to display the XUPorter license in my games that I've built using XUPorter? I don't believe this is the case from my reading of the license, as it's part of the build process but not incorporated into the code final product itself (unless Unity includes compiled editor scripts in the final application, but I should hope not.) But I wanted to check on your intentions here.

**Comment by onevcat** [comment]
No, no need to do so. :)
