### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by bailu1901** [onevcat/XUPorter#51]
I want to use [Sourcegraph](https://sourcegraph.com) for XUPorter code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/onevcat/XUPorter. (It should only take 30 seconds.)

Thank you!

**Comment by onevcat** [comment]
Enabled, but it says C# is not supported. So I wonder whether it could be used...
